name: pick_n_pay  # ⚠️ Must stay snake_case
description: A Flutter app for Pick&Pay
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.7
  http: ^1.5.0
  provider: ^6.1.5+1

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
